# Generated by Django 2.1.3 on 2018-11-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181109_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
