# Generated by Django 2.1.3 on 2018-11-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20181109_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProfileImage',
        ),
    ]
