# Generated by Django 2.1.3 on 2018-11-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20181109_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Profile', verbose_name='Пользователь'),
        ),
    ]
