# Generated by Django 2.1.3 on 2018-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_auto_20181109_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_image/default.png', upload_to='profile_image/'),
        ),
    ]
