# Generated by Django 2.1.3 on 2018-11-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20181112_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='is_main',
        ),
    ]
